name: Test SSH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH command
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
          chmod 600 key
          ssh -o StrictHostKeyChecking=no -i key ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "echo Hello from VPS && pwd"
